<#
.SYNOPSIS
    Recursively scans a KSP GameData folder for RESOURCE_DEFINITION nodes 
    containing the word "Water", exports them to a single file, and logs the relative path.
#>

# --- CONFIGURATION ---
# IMPORTANT: Ensure this path does NOT end with a trailing slash for the path calculation to work perfectly.
$TargetFolder = "H:\SteamLibrary\steamapps\common\Kerbal Space Program\GameData"  
$OutputFile = ".\Water_Resource_Definitions.cfg"

# --- SCRIPT ---

Write-Host "Scanning '$TargetFolder' for RESOURCE_DEFINITION nodes containing 'Water'..." -ForegroundColor Cyan

# 1. Prepare the Output File
$Header = @"
// Compiled Resource Definitions
// Generated by PowerShell Script
// Source Root: $TargetFolder
// Search Term: "Water"
// --------------------------------------------------------

"@
Set-Content -Path $OutputFile -Value $Header -Encoding UTF8

# 2. Define the Regex for Balanced Groups
$Pattern = '(?s)RESOURCE_DEFINITION\s*\{(?>[^{}]+|\{(?<Depth>)|\}(?<-Depth>))*(?(Depth)(?!))\}'

# 3. Get all .cfg files recursively
$CfgFiles = Get-ChildItem -Path $TargetFolder -Filter "*.cfg" -Recurse

$FoundCount = 0

foreach ($File in $CfgFiles) {
    # 4. Read the file
    $Content = Get-Content -Path $File.FullName -Raw -ErrorAction SilentlyContinue

    # Safety: Skip empty or unreadable files
    if ([string]::IsNullOrWhiteSpace($Content)) {
        continue
    }

    # 5. Calculate Relative Path
    # This strips the base $TargetFolder part from the full path
    $RelativePath = $File.FullName.Substring($TargetFolder.Length)

    # 6. Find all RESOURCE_DEFINITION blocks
    $RegexMatches = [regex]::Matches($Content, $Pattern, "IgnoreCase")

    foreach ($Match in $RegexMatches) {
        $NodeContent = $Match.Value
        
        # 7. Check if the block contains "Water"
        if ($NodeContent -match "Water") {
            
            $OutputEntry = @"
// Found in: $RelativePath
$NodeContent

"@
            Add-Content -Path $OutputFile -Value $OutputEntry
            $FoundCount++
        }
    }
}

Write-Host "Done!" -ForegroundColor Green
Write-Host "Found $FoundCount matching nodes."
Write-Host "Results saved to: $((Resolve-Path $OutputFile).Path)"